### ISSUE TITLE
Why is the program-generated Traditional Chinese Region the system default font? 

### ISSUE THREAD

**Issue by zombie6631** [mistzzt/DynamicSpriteFontGenerator#2]
![SampleFont_94](https://github.com/mistzzt/DynamicSpriteFontGenerator/assets/121270069/c21a3721-a175-4fc5-b94b-be16741d28c4)
My font contains Traditional Chinese font library. Although Terraria does not support Traditional Chinese, I hope that the generated .xnb font supports Traditional Chinese fonts.

**Comment by mistzzt** [comment]
iirc there is a parameter where you can specify the range of characters to compile. However, I don't quite remember how to do that. You probably need to decompile [ReLogic.Content.Pipeline.dll](https://github.com/mistzzt/DynamicSpriteFontGenerator/blob/master/References/ReLogic.Content.Pipeline.dll) and check the internal API.

I no longer maintain this. I appreciate any solution from the community.
